const { BasePage } = require('./BasePage');

class ScheduleLocatorsPage extends BasePage {
  constructor(page) {
    super(page);

    this.locators = {
      email: '#email',
      password: '#password',
      loginButton: '.MuiButton-label',
      setting:'//span[.="Settings"]',
      scheduling: '//a[contains(.,"Online Scheduling")]',
      schedulingLink: '//a[.="Scheduling LinkUpdated!"]',
      link: '//a[@href="https://qa10.meetkasper.com/schedule-appointment"]',
      patient: '//span[.="Returning Patient"]',
      visitReason: '//button[.="Dimple Diabeties"]',
      anyProvider: '//div[@class="MuiPaper-root PatientProviderInfo_anyProviderContainer__tI7GJ MuiPaper-elevation1 MuiPaper-rounded"]',
      time: '//*[.="Fri, Aug 21"]/ancestor::*[contains(@class,"row")]//*[contains(@class,"slot")]/button[4]',
      firstName: '//*[@name="firstName"]',
      lastName: '//*[@name="lastName"]',
      DOB: '//*[@placeholder="MM/DD/YYYY"]',
      phone: '//*[@id="phone"]',
      continueButton: '//span[.="Continue"]',
      radio: '//input[@name="haveInsurance" and @value="No"]',
      radioYes: '//input[@name="haveInsurance" and @value="Yes"]',
      radioSubscriberNo: '//input[@name="isPatientPrimarySubscriber" and @value="No"]',
      radioSubscriberYes: '//input[@name="isPatientPrimarySubscriber" and @value="Yes"]',
      otpCode: '//*[@autocomplete="one-time-code"]',
      verify: '//span[.="Verify"]',
      select: '//span[contains(.,"Gurpreet 2mwh Kaur")]',
      submitContinue: '//span[contains(.,"Continue")]',
      patientEmail: '//*[@id="patientEmail"]',
      checkAgree: '//*[@name="agreeTerms"]',
      scheduleAppointmant: '//span[.="Schedule Appointment"]',
      communication: 'xpath=//*[@href="/dashboard/patient-feed"]',
      search: 'xpath=//div[contains(@class, "MuiInputBase-root")]//input',
      appointmentverify: '//div[@class="MuiGrid-root mb-1 MuiGrid-container"]',
      dashboard: '//span[.="Dashboard"]',
      addAppointment: '//p[.="Add Appointment"]',
      cancel: '//span[.="Cancel"]',
      searchagain: '//*[@placeholder="Search..."]',
      checkpatient: '//*[@aria-labelledby="enhanced-table-checkbox-0"]',
      addButton: '//span[.="Add"]',
      officeChat: '//span[.="Office Chat"]',
      search3: 'xpath=//input[@placeholder="Search..."]',
      searchClick1:'//div[.="Gurpreet Kaur"]',
      searchClick: '//p[.="DImple Bakshi"]',
      enterMessage: '//textarea[@id="customMessage"]',
      enter: '//div[@class="HUIc+0ETHgWVoDivPrddeg=="]',
      createChat: '//button[@aria-controls="long-menu"]',
      newChat: '//span[.="New chat"]',
      name1: '//span[.="gurpreet@meetkasper.com"]',
      name2:'//span[.="dimple@meetkasper.com"]',
      doneClick: '//span[.="Done"]', 
      menu: '//button[@id="long-button"]',
      reply: '//span[.="Reply"]',
      fax: '//span[.="Fax"]',
      sendFax: '//button[.="Send Fax"]',
      savedContacts: '//span[.="Saved Contacts"]',
      select: '//*[@aria-labelledby="enhanced-table-checkbox-0"]',
      addContact: '//div[contains(@class, "MuiDialogActions-root")]//button[contains(., "Add")]',
      addCover: '//button[contains(text(),"Add")]',
      template: '//img[@src="https://faxstorage.net/storage/coverpages/1b6ba35a-146a-43c7-8d47-f70b75906290.png"]',
      recipientName: '//*[@id="recipientName"]',
      senderName:'//*[@id="senderName"]',
      subject:'//*[@id="subject"]',
      notes: '//textarea[@placeholder="Additional notes"]',
      saveIt: '//span[.="Save"]',
//button[@class="MuiButtonBase-root MuiButton-root MuiButton-contained secondary-btn MuiButton-containedSecondary"]      upload: '//span[@class="MuiButtonBase-root MuiButton-root MuiButton-text FileUpload_uploadButton__1Xqsx MuiButton-textSizeSmall MuiButton-sizeSmall"]',
      sendIt: '',
      communicationForm: '//div[@automation="communication.forms"]',
      formAction: '//div[contains(@class, "Forms_actionMenuButton")]',
      clearForm: '//span[.="Clear Forms"]',
      yesClear: '//span[contains(.,"Yes, Clear")]',
      checkMenu:'input[aria-labelledby*="enhanced-table-checkbox-0"]',
      addForm: '//span[.="+ Add Form"]',
      addIt: '//span[normalize-space()="Add"]',
      copyLink: '//span[contains(.,"Copy Link")]',
      iAgree: '//span[contains(.,"I Agree")]',
      deletePhoto: '//span[.="Delete"]',
      deleteConfirm: '//button[@class="MuiButtonBase-root MuiButton-root MuiButton-contained secondary-btn MuiButton-containedSecondary"]',
      uploadPhoto: '//span[@class="UploadImage_highlight__3W9Wm"]',
      cropSave: '//span[.="Crop & Save"]',
      canvas: '//canvas[contains(@class,"signature-pad-canvas")]',
      newSubmit: '//button[@name="data[submit]"]',
      profile:'//*[normalize-space()="Profile"]',
      formANDfile: '//span[contains(.,"Forms & Files")]',
      fileDirectory: '//p[.="File Directory"]',
      filter: '//span[@class="Table_filerIconContainer__1wKW-"]',
      close: '//span[.="Close"]',
      newPatient: '//span[.="New Patient"]',
      newTime: '//*[.="Mon, Oct 5"]/ancestor::*[contains(@class,"row")]//*[contains(@class,"slot")]/button[13]',
      chatBox: '//div[@class="MyMessageCollection_messageText__36Qra"]',
      policyFirstName: '//*[@id="policyHolderFirstName"]',
      policyLastName: '//*[@id="policyHolderLastName"]',
      policyBirthDate: '//*[@name="policyHolderBirthDate" and @placeholder="MM/DD/YYYY"]',
      selectInsuranceCheck: '//div[.="Select Insurance"]',
      selectFirstCheck: '//li[@class="MuiButtonBase-root MuiListItem-root MuiMenuItem-root MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button"][1]',
      subscriberID: '//*[@placeholder="Subscribers ID #"]',
      groupNumber: '//*[@placeholder="Group Number"]',
      employer:'//*[@placeholder="Employer"]',
      insurancePhone: '//input[@id="insurancePhone"]',
      audit: '//span[.="Audit"]',
      hiddenDetails: '//tbody/tr[1]/td[6]//*[self::button or @role="button" or local-name()="svg"]',
      details: '//div[.="Details"]',
      detailsClose: '//span[.="Close"]',
      appointmentDetails: '//div[@class="d-flex justify-content-between"]',
      closePage: '//span[.="Close"]',
      verifyFirstName: '//b[.="Patient First Name:"]',
      verifyLastName: '//b[.="Patient Last Name:"]',
      verifyEmail:'//b[.="Patient Email:"]',
      verifyDOB: '//b[.="Patient Date of Birth:"]',
      verifyAll: '//div[contains(@class, "MuiDialogContent-root") and contains(@class, "mx-5")]',
      payment: '//span[.="Payments"]',
      commPayment: '//div[@data-testid="tooltip-component" and @title="Payments"]',
      processPayment: '//span[.="Process Payment"]',
      patientPayment: '//div[.="Patient Payment"]',
      customAmount: '//div[@class="ModalPaymentOptions_radio__3bUep"]',
      fillAmount: '//input[@placeholder="0.00"]',
      confirm: '//div[.="Ok"]',
      allList: '//input[@type="checkbox" and @aria-label="decorative checkbox"]',
      uncheckit: '//span[@class="MuiButtonBase-root MuiIconButton-root jss338 MuiCheckbox-root MuiCheckbox-colorSecondary jss1281 jss339 Mui-checked MuiIconButton-colorSecondary"]',
      contPayment: '//span[.="Continue to Payment"]',
      nameOfCard: '//input[@name="manualEntry.nameOnCard"]',
      cardNumber: '//input[@name="manualEntry.cardNumber"]',
      validThrough: '//input[@name="manualEntry.expirationDate"]',
      CVV: '//input[@name="manualEntry.cvv"]',
      PostalZip: '//input[@name="manualEntry.postal"]',
      proPay: '//button[@class="MuiButtonBase-root MuiButton-root MuiButton-contained secondary-btn MuiButton-containedSecondary"]',
      uncheckEmail: '//span[.="Email"]',
      SendButton:'//span[.="Send"]',
      chatRefresh: '//span[@class="MuiBadge-badge jss173 MuiBadge-anchorOriginTopRightRectangular MuiBadge-invisible MuiBadge-dot"]',
      refundProcess: '//button[@class="MuiButtonBase-root MuiButton-root MuiButton-text PaymentsForms_buttonDots__-v5Am"]',
      refundClick: '//span[.="Void/Refund"]',
      mssgText: '//textarea[@placeholder="Message..."]',
      processRefund: '//span[.="Process Refund"]',
      yesButton: '//span[.="Yes"]',
      linkToPay: '//span[.="Link to Pay"]',
      sendLink: '//span[.="Send Link"]',
      copyLinkToPay: '//span[@data-testid="tooltip-component" and @title="Copy"]',
      linkCardName: '//input[@name="manualEntry.name"]',
      linkCardNumber: '//input[@name="manualEntry.cardNumber"]',
      linkValidThrough: '//input[@name="manualEntry.expirationDate"]',
      linkCVV: '//input[@name="manualEntry.cvv"]',
      linkPostalZip: '//input[@name="manualEntry.postal"]',
      LinkPaymentButton: '//button[.//span[contains(text(), "Process Payment")]]',
      paymentTextMssg: '//textarea[@name= "message" and @class="MentionInputField_mentions__input__oLAZd"]',
      userManagement: '//*[.="User Management"]',
      editDetails: '//span[.="dimple+15apr@meetkasper.com"]/ancestor::tr//td[@class="MuiTableCell-root MuiTableCell-body"][4]//div[@class="ActionsMenu_selectMenu__hsXVp"]',
      editPermission: '//div[@class="ActionsMenu_menuItemIcon__2jl5x"]',
      userTypeDrop: '//div[@id="accountType"]',
      adminUser: '//li[@data-value="Admin"]',
      generalUser: '//li[@data-value="General User"]',
      userType: '//span[.="dimple+15apr@meetkasper.com"]/ancestor::tr//td[@class="MuiTableCell-root MuiTableCell-body"]',
      updateUser:'//span[.="Update"]',
      activeInactive: '//span[.="dimple+15apr@meetkasper.com"]/ancestor::tr//td//div[@class="Menu_selectMenu__1BZJV"]',
      changeInactive: '//li[@class="MuiButtonBase-root MuiListItem-root MuiMenuItem-root Menu_menuItem__31ZZx MuiMenuItem-gutters MuiListItem-gutters MuiListItem-button"]',
      radioEditPermission: '//input[@type="checkbox" and contains(@class, "MuiSwitch-input")]',
      radioViewAnalytics: '//p[text()="View Analytics"]/following::input[@type="checkbox" and contains(@class, "MuiSwitch-input")][1]',
      radioThirdParty: '//p[text()="Third Party Integrations"]/following::input[@type="checkbox" and contains(@class, "MuiSwitch-input")][1]',
      radioTasks: '//p[text()="Tasks"]/following::input[@type="checkbox" and contains(@class, "MuiSwitch-input")][1]',
      paperlessForm: '//span[.="Paperless Forms"]',
      groupClick: '//div[.="test group-1sdf"]',
      renameClick: '//div[.="test group-1sdf"]//div[@class="Menu_selectMenu__3dTAq"]',
      renameClickAgain: '//div[.="testing group-1sdf"]//div[@class="Menu_selectMenu__3dTAq"]',
      renameIt: '//div[.="Rename"]',
      renameTextBox: '//*[@id="group_name"]',
      renameButton: '//span[.="Rename"]',
      archiveGroup: '//div[.="Archive"]',
      archives: '.PaperlessFormGroups_subHeaderContainer__2PfxZ button path',
      archivesOptions: '//div[@class="Menu_root__2lMif"]',
      unarchive: '//div[.="Unarchive"]',
      allSections: '//div[.="All Sections"]',
      formCheckBox: '//span[@class="jss42542"]',
      placementForApprovalCheck: '//div[normalize-space(text())="Approval for Placement"]/ancestor::div[contains(@class, "w-100")]//input[@type="checkbox"]',
      cancellationPolicyCheck: '//div[normalize-space(text())="Cancellation Policy"]/ancestor::div[contains(@class, "w-100")]//input[@type="checkbox"]',
      informationConsentCheck: '//div[normalize-space(text())="Informed Consent for Apicoectomy"]/ancestor::div[contains(@class, "w-100")]//input[@type="checkbox"]',
      noticeOfPrivacyCheck: '//div[normalize-space(text())="Notice of Privacy Practices"]/ancestor::div[contains(@class, "w-100")]//input[@type="checkbox"]',
      paperlessAction: '//span[.="Action"]',
      paperlessActionAddToGroup: '//span[.="Add to Group..."]',
      moveToGroup: '//span[normalize-space(text())="test group-1sdf"]/ancestor::*[1]//input[@type="checkbox"]',
      addToGroupButton: '//span[.="Add"]',
      paperlessActionSendToPatient: '//span[.="Send These to Patient..."]',
      sendToPatientSearch: '//div[@class="SendFormsToPatients_searchBar__1d5p1"]',
      checkSMS:'//span[normalize-space(text())="SMS"]/ancestor::*[1]//input[@type="checkbox"]',
      sendToPatientButton: '//span[.="Send"]',
      commFormContainer: '//div[@class="Forms_formsSubContainer__3689D"]',
      task: '//span[.="Tasks"]',
      addtask: '//div[contains(text(),"+ Add Task")]',
      taskName: '//textarea[@id="task_name"]',
      assigned: '//div[@id="assigned_to_id"]',
      drop: '//li[.="Dimple15Apr"]',
      drop1: '//li[.="DImple Bakshi"]',
      taskDropSearch: '//input[@placeholder="Start typing..."]',
      patient2: '//*[@id="mui-74898"]',
      category: '//*[@id="tags-input-field"]',
      create: '//span[.="Create"]',
      taskToDo: '//span[contains(text(),"To do")]',
      taskCompleted: '//span[contains(text(),"Completed")]',
      taskToDoCheck: '//div[normalize-space(text())="Task 1"]/ancestor::*[1]//input[@type="checkbox"]',
      taskCompletedThreeDots: '//*[contains(@class,"menuIcon")][1]',
      taskCompletedEditTask: '//li[text()="Edit Task"]',
      taskCompletedDelete: '//li[text()="Delete"]',
      taskCompletedMarkAsIncomplete:'//li[text()="Mark as Incomplete"]',
      editTaskSave: '//span[.="Save"]',
      calendar: '//span[.="Calendar"]',
      calAnyOperator: '//button[.//span[text()="Any Operatory"]]',
      calOperatorCheck: '//span[text()="Op 2"]',
      calOP2Container: '//div[.//p[text()="Op 2"]]//div[@data-testid="tooltip-component"][2]',
      calScheduleAppointmantButton: '//span[text()="Schedule appointment"]',
      calTimeLength: '//button[@class="MuiButtonBase-root MuiIconButton-root MuiAutocomplete-popupIndicator"]',
      calTimeSlot1: '//span[text()="Mon, Oct 5"]/ancestor::div[contains(@class, "OperatoryOpenings_dateLabel") or contains(@class, "day-column")]/following-sibling::*//button[contains(@class, "OperatoryOpenings_slotButton__1yb0d") and .//span[text()="12:00 PM"]]',
      calTimeSlot2: '//span[text()="Mon, Oct 5"]/ancestor::div[contains(@class, "OperatoryOpenings_dateLabel") or contains(@class, "day-column")]/following-sibling::*//button[contains(@class, "OperatoryOpenings_slotButton__1yb0d") and .//span[text()="4:00 PM"]]',
      calExistingPatient:'//button[.="Existing patient"]',
      calNewPatient:'//button[.="New patient"]',
      calExistingPatientSearch: '//input[@placeholder="Search by patient name or email…"]',
      existingPatientSelect: '//button[@class="CalendarSlotPopup_resultCard__1X1Wg" and .//div[text()="trevor scott"]]',
      compExam: '//span[.="Comp Exam"]',
      perExam: '//span[.="Per Exam"]',
      LimExam: '//span[.="Lim Exam"]',
      calScheduleFinal: '//span[.="Schedule"]',
      calScheduleNow: '//div[contains(@class, "ScheduleAppointment_durationActions")]//button[.//span[text()="Schedule"]]',
      calBlankScheduleClick: '//div[contains(@class, "Scheduling_cellHeaderContainer") and .//p[text()="Op 2"]]/ancestor::div[contains(@class, "Scheduling_column") or contains(@class, "col")]//div[@data-testid="tooltip-component" and @title="Click here to schedule"][5]',
      calScheduleFirstName: '//input[@id="firstname"]',
      calScheduleLastName: '//input[@id="lastname"]',
      calSchedulePhone: '//input[@id="phone"]',
      calScheduleDOB: '//input[@id="date-picker-dialog"]',
      calScheduleEmail: '//input[@id="email"]',
      calHaveInsuarance: '//input[@name="haveInsurance" and @value="Yes"]',
      calPrimarySubscriber: '//input[@name="isPatientPrimarySubscriber" and @value="Yes"]',
      calContinue: '//span[.="Continue"]',


    };
  }}
  module.exports = { ScheduleLocatorsPage }
